# 主题配色
theme_color:
  dark: "#8eaccd" # dark
  light: "#ff8080" # light

# 字体
font:
  font-size: 16px
  code-font-size: 16px
  # Global font
  # 全局字体
  font-family: "LXGW WenKai Mono GB Screen,PingFang SC, Hiragino Sans GB, Microsoft YaHei"
  # Code font
  # 代码字体
  code-font-family: "LXGW WenKai Mono GB Screen"

# 背景图片
# Background
background:
  enable: false
  opacity: .2
  dark: https://i.pinimg.com/originals/d8/b3/9d/d8b39d12b653810db452c437211aeb2e.png
  light: https://i.pinimg.com/originals/93/57/38/935738ed9657b296c2ef0ebd2151eb66.jpg

# 站点配置
home: # 在主页显示的侧边栏信息
  noSticky: about
  Sticky: allInfo

# Post default settings
# 文章默认设置
post:
  default:
    # The cover of the article is displayed
    # 文章封面显示
    top_cover: true
    # Default image when no cover is set
    # 未设置封面时的默认图片
    cover:
      # -  # 默认图片 / default cover
    # Location
    # 位置
    locate: 南昌
    # Copyright
    # 版权
    copyright:
      enable: true
      author:
        url: https://everfu.cn # Author link
        # Default use site.icon
        # 默认使用 site.icon
        img: https://ui.everfu.cn/avatar/20240827172640.png/banner
      # License
      # 许可证
      license: CC BY-NC-SA 4.0
      # License link
      # 许可证链接
      licenurl: https://creativecommons.org/licenses/by-nc-sa/4.0/deed.zh
  # Article meta information
  # 文章元信息
  meta:
    # Release date
    # 发布日期
    date: true
    # Update date
    # 更新日期
    updated: true
    # Location
    # 位置
    locate: true
    # Number of words
    # 字数
    wordcount: true
    # uv
    readtime: true
    # pv
    pv: true
    # Comment count
    # 评论数
    comment: true
  # Reward
  # 打赏
  award:
    enable: true
    appreciators: /about/ # Reward page
    # Reward Title
    # 打赏标题
    title: 感谢您的赞赏
    desc: 由于您的支持，我才能够实现写作的价值。
    # Reward list
    # 打赏列表
    list:
      # - name: Github Sponsor
      #   qcode: https://s3.qjqq.cn/47/661ba900c4bc1.webp!color
      #   url: https://github.com/sponsors/everfu
      #   color: var(--efu-black)
      - name: 微信
        qcode: https://ui.everfu.cn/avatar/202408291335398.png/cover
        url: https://s3.qjqq.cn/47/663742bac8e52.webp!color
        color: var(--efu-green)
      - name: 支付宝
        qcode: https://ui.everfu.cn/avatar/202408291338530.png/cover
        url: https://s3.qjqq.cn/47/66d00a4c7107d.png!color
        color: var(--efu-blue)

  # Share icon
  # 分享图标
  share:
    enable: false
    list:
      # - qq
      # - weibo
      # - twitter
      # - facebook
      # - telegram
      # - whatsapp
      # - linkedin
      # - link
      # - qrcode
  rss: /atom.xml
  # Article reading progress
  # 文章封面取色
  covercolor:
    enable: true
    # local: local color / api: api color / ave: oss covercolor
    mode: ave
    # api address / api 地址
    api: https://api.qjqq.cn/api/Imgcolor?img=
    # Storage / 缓存时间
    time: 43200000
  footer:
    enable: false
    desc: # Articles from Ever Fu. / 文章来自 Ever Fu # description
    button: # Button
      enable: true
      name: # Learn more / 了解更多
      url: /about/

# Page default settings
# 页面默认设置
page:
  # 404 page
  # 404 页面
  error: true
  # Tags page
  # 标签页面
  tags: true
  # Categories page
  # 分类页面
  categories: true
  # list: Sort List / 1: Follow HomeList
  # list: 排序列表 / 1: 跟随首页列表
  archives: 0
  # Default value
  # 默认值
  default:
    # Default image when no cover is set
    # 未设置封面时的默认图片
    cover:
      # - /img/default.png # 默认图片 / default cover

# Site information
# 网站信息
site:
  name:
    class: text # text / i_class / img
    custom: ped-Yc's Blog # Solitude / fas fa-ghost / /img/pwa/favicon.ico
  icon: https://ui.everfu.cn/c625e37b3cf9054d92a52ec04ce8abf0.png/avatar # Site icon / 网站图标

# Navigation bar
# 导航栏
nav:
  # Left Box
  # 左侧盒子
  group:
    我的:
      个人主页: https://everfu.cn || https://ui.everfu.cn/c625e37b3cf9054d92a52ec04ce8abf0.png/avatar
    # 项目:
    #   Solitude: https://github.com/everfu/hexo-theme-solitude || https://ui.everfu.cn/cover/202408301243345.webp/avatar
  # Menu
  # 菜单
  menu:
    # 首页: / # name: link
    文库: # name
      全部文章: /archives/ || fas fa-folder-closed # item name: link || icon
      分类列表: /categories/ || fas fa-clone
      标签列表: /tags/ || fas fa-tags
    友链:
      文章矩阵: https://summary.zhheo.com/static/matrix-posts.html || fas fa-wifi
      友情链接: /links/ || fas fa-user-group
      宝藏博主: javascript:travelling() || fas fa-gift
    我的:
      我的装备: /equipment/ || fas fa-tools
      # 在线工具: /tlink/ || fas fa-toolbox
      关于本站: /about/ || fas fa-user
  # Right button
  # 右侧按钮
  right:
    random: false # Random article / 随机文章按钮
    custom:
      # - name: 开往 # name
      #   url: https://www.travellings.cn/go.html # Jump link
      #   icon: fas fa-train # Icon
      #   onclick: # Click event
      #   id: travellings_button # id

# Home Top Banner
# 首页顶部
hometop:
  enable: true
  banner:
    title: 路漫漫其修远兮<br> 吾将上下而求索
    url: 记录、分享、成长
    icon:
      Nodejs:
        img: https://ui.everfu.cn/cover/20240827172946.png/cover
        color: "#242938"
      Vue:
        img: https://ui.everfu.cn/cover/20240827173146.png/cover
        color: "#242938"
      React:
        img: https://ui.everfu.cn/avatar/20240827172839.png/cover
        color: "#242938"
      HTML:
        img: https://ui.everfu.cn/cover/20240827173208.png/cover
        color: "#e34c26"
      CSS:
        img: https://ui.everfu.cn/cover/20240827173227.png/cover
        color: "#0277BD"
      JavaScript:
        img: https://ui.everfu.cn/cover/20240827173248.png/cover
        color: "#EFDB50"
  group:
    # 热门: /tags/Fire/ || fas fa-fire || linear-gradient(to right,#f65,#ffbf37)
  recommendList:
    sup: 置顶
    title: 我的数字花园
    url: https://dg.ped-yc.site
    img: https://ui.everfu.cn/cover/20240827173743.png/cover
    color: "none"

# Information card
# 信息卡
card:
  style: 0 # 0: default 1: style 1 2: style 2
  author:
    img: https://ui.everfu.cn/avatar/20240827172640.png/banner
    url: https://everfu.cn # link / 点击头像跳转链接
  background: # https://s3.qjqq.cn/47/663af296b85f4.webp!color # Background image(Invalid if style is 0)
  # Content(Invalid if style is 0)
  # 内容(Style 0 无效)
  content: 这是我分享自己写作的一个平台 # 这是我的博客 / This is my Blog
  content2: 我是一个热爱开源的小子 # 一个热爱生活的人 / A person who loves life
  # Style 2 is invalid
  # Style 2 无效
  sayhello:
    morning: ✨ 早上好，新的一天开始了
    noon: 中午饭时间
    afternoon: 下午茶时间 ☕️
    night: 不要熬夜哦
    goodnight: 晚安，早点休息
  # Style 2 is invalid, Triggered when sayhello is clicked.
  # Style 2 无效, 点击 sayhello 时触发
  sayhello2:
    - 你可以的
    - 相信你可以的
    - 你一定可以的
  # social
  # 社交信息图标
  information:
    Github: https://github.com/everfu || fab fa-github # Name: link || icon
    Bilibili: https://space.bilibili.com/1329819902 || fab fa-bilibili

# URL
## Set your site url here. For example, if you use GitHub Page, set url as 'https://username.github.io/project'
url: https://ped-yc.github.io/
permalink: :year/:month/:day/:title/
permalink_defaults:
pretty_urls:
  trailing_index: true # Set to false to remove trailing 'index.html' from permalinks
  trailing_html: true # Set to false to remove trailing '.html' from permalinks

# Directory
source_dir: source
public_dir: public
tag_dir: tags
archive_dir: archives
category_dir: categories
code_dir: downloads/code
i18n_dir: :lang
skip_render:

# Writing
new_post_name: :title.md # File name of new posts
default_layout: post
titlecase: false # Transform title into titlecase
external_link:
  enable: true # Open external links in new tab
  field: site # Apply to the whole site
  exclude: ""
filename_case: 0
render_drafts: false
post_asset_folder: true
marked:
  prependRoot: true
  postAsset: true
relative_link: false
future: true
highlight:
  enable: true
  line_number: true
  auto_detect: false
  tab_replace: ""
  wrap: true
  hljs: false
prismjs:
  enable: false
  preprocess: true
  line_number: true
  tab_replace: ""

# Home page setting
# path: Root path for your blogs index page. (default = '')
# per_page: Posts displayed per page. (0 = disable pagination)
# order_by: Posts order. (Order by date descending by default)
index_generator:
  path: ""
  per_page: 10
  order_by: -date

# Category & Tag
default_category: uncategorized
category_map:
tag_map:

# Metadata elements
## https://developer.mozilla.org/en-US/docs/Web/HTML/Element/meta
meta_generator: true

# Date / Time format
## Hexo uses Moment.js to parse and display date
## You can customize the date format as defined in
## http://momentjs.com/docs/#/displaying/format/
date_format: YYYY-MM-DD
time_format: HH:mm:ss
## updated_option supports 'mtime', 'date', 'empty'
updated_option: "mtime"

# Pagination
## Set per_page to 0 to disable pagination
per_page: 10
pagination_dir: page

# Include / Exclude file(s)
## include:/exclude: options only apply to the 'source/' folder
include:
exclude:
ignore:

# Extensions
## Plugins: https://hexo.io/plugins/
## Themes: https://hexo.io/themes/
theme: solitude

# Deployment
## Docs: https://hexo.io/docs/one-command-deployment
deploy:
  type: git
  repo: https://github.com/ped-Yc/ped-Yc.github.io.git
  branch: master
